name: .NET Build, Test and Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore WindowsApp.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build solution
      run: msbuild WindowsApp.sln /p:Configuration=Release

    - name: Install VSTest Console
      uses: darenm/Setup-VSTest@v1


  codeql-analysis:
    name: CodeQL Analysis
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
  
    - name: Restore NuGet packages
      run: nuget restore WindowsApp.sln      

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    - name: Build code
      run: msbuild WindowsApp.sln /p:Configuration=Release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  snyk-security:
    name: Snyk Security Analysis
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Snyk
      uses: snyk/snyk-action@v1

    - name: Authenticate with Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk test for vulnerabilities
      run: snyk test --all-projects

    - name: Monitor project with Snyk
      run: snyk monitor --all-projects
