name: .NET Framework Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore WindowsApp.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build solution
      run: msbuild WindowsApp.sln /p:Configuration=Release

    - name: Run unit tests with VSTest
      run: |
        $testDll = Get-ChildItem -Recurse -Filter "ConverterApp.Tests.dll" | Select-Object -First 1
        if ($testDll) {
          vstest.console.exe $testDll.FullName
        } else {
          Write-Error "Test DLL not found!"
          exit 1
        }
