name: Snyk Vulnerability Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore WindowsApp.sln

      - name: Install Snyk CLI (manual installation)
        run: |
          curl -sL https://github.com/snyk/snyk/releases/download/v1.515.0/snyk-win.zip -o snyk.zip
          unzip snyk.zip -d snyk
          mv snyk/snyk.exe $GITHUB_PATH

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test (vulnerability scan)
        run: snyk test --file=WindowsApp.sln --all-projects --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor project in Snyk (optional)
        run: snyk monitor --file=WindowsApp.sln --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
