name: .NET Build, Test and Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore WindowsApp.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build solution
      run: msbuild WindowsApp.sln /p:Configuration=Release

    - name: Install VSTest Console
      uses: darenm/Setup-VSTest@v1

    - name: Run unit tests with coverage and generate report
      run: |
        $testDll = Get-ChildItem -Recurse -Filter "ConverterApp.Tests.dll" | Select-Object -First 1
        $resultsDir = "TestResults"
        mkdir $resultsDir
        vstest.console.exe $testDll.FullName /Settings:coveragerunsettings.runsettings /Logger:trx /ResultsDirectory:$resultsDir /EnableCodeCoverage

    - name: Upload test report artifact
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: TestResults/*.trx

    - name: Upload code coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: CodeCoverage
        path: TestResults/*.coverage
